name: Test
on:
  push:
    branches:
      - '**'

  pull_request:

  schedule:
    - cron: '17 5 * * *'

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2

      - run: go generate

      - run: go test -race -coverprofile=coverage.txt ./...

      - run: go run ./lib/utils/check-cov

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cdp-log-linux
          path: |
            tmp/cdp-log
            coverage.txt

  test-other-os:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - run: go test -race -timeout-each=2m

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cdp-log-${{ matrix.os }}
          path: tmp/cdp-log

  test-old-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      # As long as the build works we don't have to run tests.
      - run: go build ./lib/examples/translator
